import difflib

def get_response(user_input, chat_memory):
    faq_data = {
        "what is your return policy?": "You can return any item within 30 days of purchase. 😊",
        "how can i contact customer support?": "You can reach customer support via email at support@example.com. 📧",
        "what are your shipping options?": "We offer standard and express shipping options. 🚚",
        "do you offer international shipping?": "Yes, we ship to select international locations. 🌍",
        "how can i track my order?": "You can track your order using the tracking link sent to your email. 📦",
        "what is python?": "Python is a high-level, interpreted programming language known for its readability and versatility. 🐍",
        "what is ai?": "AI stands for Artificial Intelligence, which is the simulation of human intelligence in machines. 🤖",
        "what is machine learning?": "Machine learning is a subset of AI that involves training algorithms to learn from data. 📊",
        "what is deep learning?": "Deep learning is a subset of machine learning that uses neural networks with many layers. 🧠",
        "what is a neural network?": "A neural network is a series of algorithms that attempt to recognize underlying relationships in a set of data. 🔗",
        "what is natural language processing?": "Natural language processing (NLP) is a field of AI that focuses on the interaction between computers and humans through natural language. 🗣️",
        "what is a chatbot?": "A chatbot is a software application used to conduct an online chat conversation via text or text-to-speech. 💬",
        "what is data science?": "Data science is a field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from data. 📈",
        "what is big data?": "Big data refers to large, complex data sets that are difficult to process using traditional data processing applications. 📊",
        "what is cloud computing?": "Cloud computing is the delivery of computing services over the internet. ☁️",
        "what is an api?": "API stands for Application Programming Interface, which allows different software applications to communicate with each other. 🔌",
        "what is a database?": "A database is an organized collection of data, generally stored and accessed electronically from a computer system. 🗄️",
        "what is sql?": "SQL stands for Structured Query Language, which is used to communicate with databases. 🗃️",
        "what is a programming language?": "A programming language is a formal language comprising a set of instructions that produce various kinds of output. 💻",
        "what is an ide?": "IDE stands for Integrated Development Environment, which is a software application that provides comprehensive facilities to computer programmers for software development. 🛠️",
        "what is github?": "GitHub is a web-based platform used for version control and collaborative software development. 🐱",
        "what is open source?": "Open source refers to software with source code that anyone can inspect, modify, and enhance. 🔓",
        "hello": "Hello! How can I assist you today? 😊",
        "hi": "Hi there! How can I help you? 😊",
        "hey": "Hey! What can I do for you today? 😊",
        "good morning": "Good morning! How can I assist you today? 😊",
        "good afternoon": "Good afternoon! How can I help you? 😊",
        "good evening": "Good evening! What can I do for you today? 😊",
        "what is a function?": "A function is a block of code that performs a specific task. 🛠️",
        "what is an algorithm?": "An algorithm is a step-by-step procedure for solving a problem or accomplishing a task. 📚",
        "what is a variable?": "A variable is a storage location identified by a memory address and an associated symbolic name. 📦",
        "what is a loop?": "A loop is a programming construct that repeats a block of code while a condition is true. 🔄",
        "what is an array?": "An array is a data structure that can hold more than one value at a time. 📊",
        "what is a class?": "A class is a blueprint for creating objects in object-oriented programming. 🏛️",
        "what is an object?": "An object is an instance of a class in object-oriented programming. 🧩",
        "what is inheritance?": "Inheritance is a feature of object-oriented programming where a class can inherit properties and methods from another class. 🧬",
        "what is polymorphism?": "Polymorphism is a feature of object-oriented programming that allows methods to do different things based on the object it is acting upon. 🔄",
        "what is encapsulation?": "Encapsulation is a feature of object-oriented programming that restricts access to certain components of an object. 🔒",
        "what is abstraction?": "Abstraction is a feature of object-oriented programming that hides complex implementation details and shows only the necessary features. 🎭",
        "what is a compiler?": "A compiler is a program that translates source code into machine code. 🖥️",
        "what is an interpreter?": "An interpreter is a program that directly executes instructions written in a programming language. 📝",
        "what is a framework?": "A framework is a platform for developing software applications. 🛠️",
        "what is a library?": "A library is a collection of precompiled routines that a program can use. 📚",
        "what is a module?": "A module is a file containing Python definitions and statements. 📦",
        "what is a package?": "A package is a collection of Python modules. 📦",
        "what is pip?": "Pip is a package manager for Python. 📦",
        "what is a virtual environment?": "A virtual environment is an isolated environment for Python projects. 🌐",
        "what is git?": "Git is a distributed version control system. 🐙",
        "what is a repository?": "A repository is a storage location for software packages. 📦",
        "what is a branch?": "A branch is a parallel version of a repository. 🌿",
        "what is a commit?": "A commit is a record of changes made to a repository. 📝",
        "what is a pull request?": "A pull request is a way to submit changes to a repository. 🔄",
        "what is a merge?": "A merge is the process of combining changes from different branches. 🔀",
        "what is a conflict?": "A conflict occurs when changes from different branches cannot be automatically merged. ⚔️",
        "what is continuous integration?": "Continuous integration is a practice where code changes are automatically tested and merged. 🔄",
        "what is continuous deployment?": "Continuous deployment is a practice where code changes are automatically deployed to production. 🚀",
        "what is a container?": "A container is a lightweight, portable, and self-sufficient environment for running applications. 🛳️",
        "what is docker?": "Docker is a platform for developing, shipping, and running applications in containers. 🐳",
        "goodbye": "Goodbye! Have a great day! 😊",
        "bye": "Bye! Take care! 😊",
        "see you later": "See you later! 😊",
        "talk to you soon": "Talk to you soon! 😊",
        "thanks": "You're welcome! 😊",
        "what is the meaning of life?": "The meaning of life is a philosophical question concerning the significance of living or existence in general. 🤔",
        "what is the answer to the ultimate question of life, the universe, and everything?": "The answer to the ultimate question of life, the universe, and everything is 42. 🌌",
        "tell me a joke": "Why do programmers prefer dark mode? Because light attracts bugs! 🐛",
        "tell me a programming joke": "Why do programmers prefer dark mode? Because light attracts bugs! 🐛",
        "i love you": "Aw, I appreciate the sentiment! 😊",
        "what is your name?": "My name is mjbot! How can I assist you today? 😊",
        "who created you?": "I was created by a developer named Mj! 😊",
        "what is your purpose?": "My purpose is to assist you with any questions you may have! 😊",
        "how are you?": "I'm just a bot, so I don't have feelings, but I'm here to help you! 😊",
        "how is the world?": "The world is a complex and diverse place with many challenges and opportunities. 🌍",
        "can you help me?": "Of course! I'll do my best to assist you. 😊",
        "can you add two numbers?": "I can't perform calculations, but I can provide information and answer questions! 😊",
        "can you sing a song?": "I'm not programmed to sing, but I can provide song recommendations! 🎵",
        
        
    }

    user_input = user_input.lower()
    closest_match = difflib.get_close_matches(user_input, faq_data.keys(), n=1, cutoff=0.6)
    response = faq_data.get(closest_match[0], "I'm sorry, I don't have an answer for that. 😔") if closest_match else "I'm sorry, I don't have an answer for that. 😔"
    chat_memory.append({"user": user_input, "bot": response})
    return response, chat_memory